### ISSUE TITLE
No way to feed the Say node with dynamic content

### ISSUE THREAD

**Issue by Megamuch** [jambonz/node-red-contrib-jambonz#12]
I'm not really sure this is an issue, but it would be useful if we could feed the Say node with msg.payload instead of static text only. 
The current Say node only allows for a static content box which it will tts. But what if data data is now dynamic and retrieved from an outside source. 

I see no way to feed that into the Say node.

**Comment by davehorton** [comment]
any thoughts on this @sammachin ?

**Comment by sammachin** [comment]
I thought the text field supported mustache templating, so you could put something like 
`The message payload is {{payload}}`
However that doesn't seem to work in my test, I'll dig into it later.

IMO Templating is a better fit for this field rather than typed inputs

**Comment by davehorton** [comment]
ah right....I think.  Can you try that @Megamuch ?

**Comment by Megamuch** [comment]
I tried the mustache template and that does not work. @sammachin what do you mean with templating?

**Comment by sammachin** [comment]
@Megamuch basically like you tested so using mustache values in the field.
I'll look into why thats not working and hopefully its a quick fix.

**Comment by sammachin** [comment]
@Megamuch I've had a chance to look at the code and that field does support templating, however it uses javascript template literals rather than mustache which I've not seen in Node-RED before.

Try using `The payload is ${msg.payload}` in the text box and you should get the payload value inserted.

I'll have a deeper look at how we could also support mustache in this field as that would be more Node-RED like in future but I don't want to remove the current format as that would be a breaking change so will need to see if/how the 2 can co-exist.

**Comment by Megamuch** [comment]
Thanks! tested this out and works. also works with flow variables in the same way.

**Comment by sammachin** [comment]
yes and global vars

**Comment by davehorton** [comment]
available in 2.3.1
